services:
  sds:
    build: .
    container_name: sds
    ports:
      - "8080:80"
      # - "443:443"
    volumes:
      - ./config.yaml:/sds/config.yaml
      - ./container_data:/sds/container_data
      - ./software.csv:/sds/software.csv
      - ./spider_data:/sds/spider_data
      - ./software_uses:/sds/software_uses
      # - ./ssl:/etc/nginx/ssl
      # Add any other files or directories you want to mount
      # - ./local_path:/container_path

