version: '3'

services:
  sds:
    build: .
    container_name: sds
    networks:
      - app_network
    # Don't expose ports to the host directly, only to nginx
    # If you need direct access for debugging, uncomment:
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "808:80"  # host_port:container_port to not conflict with standard ports on host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Uncomment for SSL:
      # - ./ssl:/etc/nginx/ssl
    depends_on:
      - sds
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
