services:
  sds:
    build: .
    container_name: sds
    networks:
      - app_network
    ports:
      - "8080:8080"
    volumes:
      - ./container_data:/sds/container_data
      - ./software.csv:/sds/software.csv
      - ./spider_data:/sds/spider_data
      # Add any other files or directories you want to mount
      # - ./local_path:/container_path
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "808:80"  # host_port:container_port to not conflict with standard ports on host
      # - "443:443" # host nd container port for https (with SSL)
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Uncomment for SSL:
      # - ./ssl:/etc/nginx/ssl
    depends_on:
      - sds
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
