[supervisord]
nodaemon=true
user=root
logfile=/sds/data/state/logs/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
stdout_logfile=/sds/data/state/logs/nginx.log
stderr_logfile=/sds/data/state/logs/nginx.log
autorestart=true

[program:sds-app]
command=/sds/entrypoint.sh
stdout_logfile=/sds/data/state/logs/sds-stdout.log
stderr_logfile=/sds/data/state/logs/sds-stdout.log
autorestart=true