name: Update from Private Repo

on:
  workflow_dispatch:

jobs:
  update-public-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repo
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Checkout private repo
      uses: actions/checkout@v3
      with: 
        repository: access-ci-org/ACCESS-SDS
        token: ${{ secrets.PAT }}
        path: private-repo

    - name: Sync files
      run: |
        rsync -av --exclude='.git' private-repo/ .
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update from private repo"
        git push origin main

    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
