name: Update from Private Repo

on:
  workflow_dispatch:

jobs:
  update-public-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Checkout private repository
      uses: actions/checkout@v3
      with:
        repository: access-ci-org/ACCESS-SDS
        token: ${{ secrets.PAT }}
        path: private-sds-repo

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Sync files
      run: |
        rclone sync private-sds-repo/ . --exclude='.git/**' --exclude='.github/**' --exclude='README.md'
        rm -r private-sds-repo

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update from private repo"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
