name: Update standalone branch

on:
  workflow_dispatch:

jobs:
  update-public-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout public repository stand-alone branch
      uses: actions/checkout@v3
      with:
        ref: stand-alone

    - name: Clone private repository
      # Must clone the directory into a file outside of where the current public repo is
      # This prevents overlapping directory issue with rclone (exit code 7)
      run: |
        mkdir -p ../private-sds-repo
        git clone -b stand-alone --single-branch https://sandesh-l:${{ secrets.PAT }}@github.com/access-ci-org/ACCESS-SDS.git ../private-sds-repo
        
    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Sync files
      # exclude the .git directory
      # exclude the .github directory because it would overwrite this github action as well
      # Remove the private-sds-repo directory just in case it tries to push that directory as well
      run: |
        rclone sync ../private-sds-repo/ . --exclude='.git/**' --exclude='.github/**' --exclude='app/data/**' --exclude='.flaskenv'
        rm -r ../private-sds-repo

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update from private repo"
        git push origin stand-alone
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
